export default {
    'fontFamily': 'Cairo Play',
    'htmlFontSize': 10,
    'h1': {
      'fontFamily': 'Cairo Play',
      'fontSize': '3.5rem !important',
      'fontWeight': 300,
      'fontStretch': 'normal',
      'fontStyle': 'normal',
      'lineHeight': 1.21428571429,
      'letterSpacing': 'normal',
    },
    'h2': {
      'fontFamily': 'Cairo Play',
      'fontSize': '3rem !important',
      'fontWeight': 300,
      'fontStretch': 'normal',
      'fontStyle': 'normal',
      'lineHeight': 1.20833333333,
      'letterSpacing': '0.01px',
    },
    'h3': {
      'fontFamily': 'Cairo Play',
      'fontSize': '2.5rem !important',
      'fontWeight': 500,
      'fontStretch': 'normal',
      'fontStyle': 'normal',
      'lineHeight': 1.225,
      'letterSpacing': '0.01px',
    },
    'h4': {
      'fontFamily': 'Cairo Play',
      'fontSize': '2rem !important',
      'fontWeight': 'bold',
      'fontStretch': 'normal',
      'fontStyle': 'normal',
      'lineHeight': 1.21875,
      'letterSpacing': '0.01px',
    },
    'h5': {
      'fontFamily': 'Cairo Play',
      'fontSize': '1.5rem !important',
      'fontWeight': 'bold',
      'fontStretch': 'normal',
      'fontStyle': 'normal',
      'lineHeight': 1.20833333333,
      'letterSpacing': '0.01px',
      'textAlign': 'left',
    },
    'h6': {
      'fontFamily': 'Cairo Play',
      'fontSize': '1rem !important',
      'fontWeight': 'bold',
      'fontStretch': 'normal',
      'fontStyle': 'normal',
      'lineHeight': 1.1875,
      'letterSpacing': 'normal',
    },
    'subtitle1': {
      'fontFamily': 'Cairo Play',
      'fontSize': '0.75rem !important',
      'fontWeight': 'bold',
      'fontStretch': 'normal',
      'fontStyle': 'normal',
      'lineHeight': 1.16666666667,
      'letterSpacing': '0.01px',
      'text-transform': 'uppercase',
    },
    'subtitle2': {
      'fontFamily': 'Cairo Play',
      'fontSize': '1rem !important',
      'fontWeight': 500,
      'fontStretch': 'normal',
      'fontStyle': 'normal',
      'lineHeight': 1.1875,
      'letterSpacing': '0px',
    },
    'body1': {
      'fontFamily': 'Cairo Play',
      'fontSize': '1rem !important',
      'fontWeight': 'normal',
      'fontStretch': 'normal',
      'fontStyle': 'normal',
      'lineHeight': 1.1875,
      'letterSpacing': '0px',
    },
    'body2': {
      'fontFamily': 'Cairo Play',
      'fontSize': '0.875rem !important',
      'fontWeight': 'normal',
      'fontStretch': 'normal',
      'fontStyle': 'normal',
      'lineHeight': 1.21428571429,
      'letterSpacing': '0.01px',
    },
    'button': {
      'fontFamily': 'Cairo Play',
      'fontSize': '0.875rem !important',
      'fontWeight': 'bold',
      'fontStretch': 'normal',
      'fontStyle': 'normal',
      'lineHeight': 1.21428571429,
      'letterSpacing': '0.01px',
    },
    'caption': {
      'fontFamily': 'Cairo Play',
      'fontSize': '0.75rem !important',
      'fontWeight': 'normal',
      'fontStretch': 'normal',
      'fontStyle': 'normal',
      'lineHeight': 1.16666666667,
      'letterSpacing': 'normal',
    },
  };
  